const jwt = require('jsonwebtoken')

//authorising users even after being authenticated just to make sure
//the generated token is still available so they can have access
//to other resources in the application

module.exports.todoAuthUser = (req, res, next) => {
    //accessing the cookie and checking the jwt availability
    console.log(req.cookies)
    

    const token = req.cookies.jwt
    console.log(token)
    //check if the token matches with the one generated by the private
    //key
    if(token) {
        jwt.verify(token, process.env.JWT_SECRET, (err, decoded) => {
            if(err) {
                console.log(err)
            } else {
                //res.json(decoded)
                console.log(decoded)
                next()
            }
        })
    }else {
        res.json("token doesn't exist")
    }
}